### ISSUE TITLE
Suggestion around ISO 3166-1

### ISSUE THREAD

**Issue by pmdci** [maxtomczyk/covid19-api#1]
Using DP for Diamond Princess and CI for Channel Islands is likely to cause issues. Which by the way, are Alpha-2 codes, and not Alpha-3 code as per the readme.

When adding codes for NON 3166-1 locations (e.g. Diamond Princess), make sure yo use USER-ASSIGNED code elements for Alpha-2 and Alpha-3.

See:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#User-assigned_code_elements

So you could use something like ZZ as Alpha-2, or anything starting with X. There are 43 possible codes that are reserved for custom usage.

As for numeric does, no number range is currently reserved. I tend to assign ISO3166-1 to SMALLINT in SQL Server (up to 32,767), so you could assign values over 30,000 or perhaps negative values.

**Comment by maxtomczyk** [comment]
Hi!
I think I can add USER_ASSIGNED codes for Diamond Princess and Channel Islands, but I'm not sure if I should remove currently existing codes as it would be breaking change. I'm going to think about it and probably implement it this weekend.

**Comment by maxtomczyk** [comment]
User-assigned codes are now live, actually using custom codes for Diamond Princess, Channel Islands and Kosovo. All codes after potential updates will be listed in README.md file in section Country codes.
