### ISSUE TITLE
404 error for USA

### ISSUE THREAD

**Issue by christena-holloway** [maxtomczyk/covid19-api#2]
The endpoint for cases in the USA is giving me a 404 error. I'm unable to test it, but I think the issue is probably with line 48 in baselab.js. I'm guessing that it's removing the row that has the data for USA since it's first row after the total

**Comment by maxtomczyk** [comment]
Hi!

Thanks for reporting. You are right. It looks like table on website change and it's not providing total outside China field anymore. I will push fix to heroku and close this issue.

**Comment by maxtomczyk** [comment]
Fixed version is running on Heroku now.
